### ISSUE TITLE
Tracing example does not show tracing info in Jaeger

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/examples#121]
**Description**
 The tracing example (https://github.com/kyma-project/examples/tree/master/tracing) does not work.
The service is deployed, few `curl` calls done, but in the jaeger console I could not sleect order-front.

**Expected result**

Jeager console allows me to select order-front and shows tracing info.

**Comment by a-thaler** [comment]
Currently, nearly no traces are sampled by istio, only 1 out of 100. For now please manually adjust the trace sampling rate to 100, see https://istio.io/docs/tasks/telemetry/distributed-tracing/overview/

See https://github.com/kyma-project/kyma/issues/4103
I like to avoid for the results of the linked issue in order to decide what to do with the example

**Comment by a-thaler** [comment]
As the trace sampling rate will never be set to 100% by default on a cluster we clearly must document how to set a value of 100 for the example.
