### ISSUE TITLE
JWT Token

### ISSUE THREAD

**Issue by sundarvc** [kyma-project/examples#169]
Hi Kyma team,

Is there a way to call a url to get JWT token like getting the Oauth token in the example ?
I am trying to have a client get the JWT token using a call instead of manual step of getting it from the kubeconfig like in the example docs.

Thanks,
Sunar

**Comment by kubadz** [comment]
Generally, ID Token (the JWT token in kubeconfig) should always be used in a user context. That is why there are no libraries to fetch it automatically from Dex, because the user always has to log in to the Identity Provider configured in Dex (and there might be multiple providers configured). And the exact authentication method may differ between providers. For example, one might require basic credentials in form of user password and email and another might use some certificate-based authentication.

That said, we do fetch the token from Dex automatically in tests. For example, [here](https://github.com/kyma-project/kyma/blob/master/tests/integration/dex/dex/idtokenprovider.go) is a code that performs an implicit flow in a way a  regular user would do. It uses a static user in Dex created for testing and it requires that static users are enabled in Dex. You can probably adjust it to any login page, but please have in mind that it is rather a workaround that might be used for simulating user behaviour in tests or automating some stuff (if you want to give it your credentials).

**Comment by Tomasz-Smelcerz-SAP** [comment]
I am closing this.
